let SITE={contractAddress:'TBA',buyUrl:'',recipient:'To be announced',defensePercent:80,operationsPercent:20,goal:100000,contributions:[]};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadSite(){try{SITE={...SITE,...await fetch('/api/config',{cache:'no-store'}).then(r=>r.json())}}catch(e){} renderSite()}
function renderSite(){let C=SITE.contributions||[],total=C.reduce((s,x)=>s+(+x.amount||0),0);$('.money').textContent=total.toLocaleString('en-US',{style:'currency',currency:'USD'});$('#meter-fill').style.width=Math.min(total/(+SITE.goal||100000)*100,100)+'%';
 document.querySelectorAll('.split b')[0].textContent=SITE.defensePercent+'%';document.querySelectorAll('.split b')[1].textContent=SITE.operationsPercent+'%';document.querySelector('.alloc-big span').textContent=SITE.defensePercent;
 let ca=$('#copy-ca');ca.dataset.ca=SITE.contractAddress||'TBA';ca.childNodes[0].nodeValue=(SITE.contractAddress||'TBA')+' ';let buy=document.querySelector('.token-actions .primary');if(SITE.buyUrl){buy.href=SITE.buyUrl;buy.textContent='BUY $NEO ↗';buy.classList.remove('disabled')}else{buy.href='#';buy.textContent='BUY $NEO — SOON';buy.classList.add('disabled')}
 let ledger=$('#ledger'),empty=$('#empty-ledger');ledger.innerHTML='';empty.style.display=C.length?'none':'grid';C.slice().reverse().forEach(x=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${esc(x.date)}</td><td>${esc(x.recipient)}</td><td>$${(+x.amount||0).toLocaleString()}</td><td>${esc(x.ref)}</td><td>${x.proof?`<a class="proof-link" href="${esc(x.proof)}" target="_blank" rel="noreferrer">VIEW ↗</a>`:'—'}</td>`;ledger.appendChild(tr)})}
$('#year').textContent=new Date().getFullYear();$('#copy-ca').onclick=async e=>{let ca=e.currentTarget.dataset.ca;if(ca==='TBA')return;await navigator.clipboard.writeText(ca);e.currentTarget.querySelector('span').textContent='COPIED';setTimeout(()=>e.currentTarget.querySelector('span').textContent='COPY',1200)};
const AU_KM=149597870.7,LD_KM=384400;
async function loadNEOs(){let grid=$('#neo-grid');try{let r=await fetch('/api/neo');if(!r.ok)throw 0;let j=await r.json(),idx=Object.fromEntries(j.fields.map((f,i)=>[f,i]));grid.innerHTML='';if(!j.data?.length)throw 0;j.data.forEach((x,n)=>{let dist=+x[idx.dist]*AU_KM,diam=x[idx.diameter]?`${(+x[idx.diameter]*1000).toFixed(0)} m`:'UNKNOWN',el=document.createElement('article');el.className='neo-card';el.innerHTML=`<span class="num">0${n+1}</span><div class="approach"></div><h3>${esc((x[idx.fullname]||x[idx.des]).trim())}</h3><dl><div><dt>CLOSE APPROACH</dt><dd>${esc(x[idx.cd])} TDB</dd></div><div><dt>MISS DISTANCE</dt><dd>${Math.round(dist).toLocaleString()} KM</dd></div><div><dt>LUNAR DISTANCE</dt><dd>${(dist/LD_KM).toFixed(2)} LD</dd></div><div><dt>REL. VELOCITY</dt><dd>${(+x[idx.v_rel]).toFixed(2)} KM/S</dd></div><div><dt>KNOWN DIAMETER</dt><dd>${diam}</dd></div><div><dt>DESIGNATION</dt><dd>${esc(x[idx.des])}</dd></div></dl>`;grid.appendChild(el)})}catch(e){grid.innerHTML='<div class="loading">TELEMETRY LINK TEMPORARILY UNAVAILABLE.<br><small>RETRYING ON NEXT LOAD.</small></div>'}}
loadSite();loadNEOs();
const c=$('#space'),ctx=c.getContext('2d');let stars=[],rocks=[],shooters=[];const rnd=(a,b)=>a+Math.random()*(b-a);
function makeRock(initial=true){let z=rnd(.35,1.35),r=rnd(5,28)*z;return{x:initial?rnd(0,innerWidth):innerWidth+r*4,y:rnd(-100,innerHeight+100),r,z,v:rnd(.18,1.05)*z,vy:rnd(-.08,.16),rot:rnd(0,7),spin:rnd(-.004,.004),pts:Array.from({length:10},(_,i)=>({a:i/10*Math.PI*2,rr:r*rnd(.7,1.25)})),shade:rnd(35,70)}}
function makeShooter(initial=true){let blue=Math.random()>.48,ang=rnd(.42,.78),speed=rnd(7,15),len=rnd(90,230);return{x:initial?rnd(0,innerWidth*1.15):rnd(innerWidth*.45,innerWidth*1.25),y:initial?rnd(-innerHeight*.15,innerHeight*.8):rnd(-180,innerHeight*.18),vx:-Math.cos(ang)*speed,vy:Math.sin(ang)*speed,len,w:rnd(.65,1.7),a:rnd(.28,.72),blue,delay:initial?rnd(0,9000):rnd(1400,11000),born:performance.now()}}
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(320,innerWidth/3)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:rnd(.15,1.2),a:rnd(.08,.65),tw:rnd(0,6.3)}));rocks=Array.from({length:11},()=>makeRock());shooters=Array.from({length:6},()=>makeShooter())}
function rock(o,t){o.x-=o.v;o.y+=o.vy;o.rot+=o.spin;if(o.x<-o.r*4)Object.assign(o,makeRock(false));ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot);ctx.beginPath();o.pts.forEach((p,i)=>{let x=Math.cos(p.a)*p.rr,y=Math.sin(p.a)*p.rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();let g=ctx.createRadialGradient(-o.r*.35,-o.r*.45,o.r*.08,0,0,o.r*1.25);g.addColorStop(0,`rgba(${o.shade+45},${o.shade+48},${o.shade+48},${.28*o.z})`);g.addColorStop(.5,`rgba(${o.shade},${o.shade+3},${o.shade+4},${.22*o.z})`);g.addColorStop(1,`rgba(4,6,7,${.35*o.z})`);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle=`rgba(145,165,170,${.12*o.z})`;ctx.stroke();if(o.r>14){ctx.fillStyle=`rgba(0,0,0,${.18*o.z})`;ctx.beginPath();ctx.ellipse(-o.r*.15,o.r*.1,o.r*.18,o.r*.11,.4,0,7);ctx.fill()}ctx.restore()}
function shooter(s,t){if(t-s.born<s.delay)return;s.x+=s.vx;s.y+=s.vy;let mag=Math.hypot(s.vx,s.vy),ux=s.vx/mag,uy=s.vy/mag,tx=s.x-ux*s.len,ty=s.y-uy*s.len;let g=ctx.createLinearGradient(s.x,s.y,tx,ty);let rgb=s.blue?'92,188,255':'255,151,70';g.addColorStop(0,`rgba(255,255,255,${s.a})`);g.addColorStop(.08,`rgba(${rgb},${s.a*.9})`);g.addColorStop(1,`rgba(${rgb},0)`);ctx.strokeStyle=g;ctx.lineWidth=s.w;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(tx,ty);ctx.stroke();ctx.fillStyle=`rgba(255,255,255,${Math.min(.95,s.a+0.2)})`;ctx.beginPath();ctx.arc(s.x,s.y,s.w*.9,0,7);ctx.fill();if(s.x<-s.len||s.y>innerHeight+s.len)Object.assign(s,makeShooter(false))}
function draw(t=0){ctx.clearRect(0,0,innerWidth,innerHeight);stars.forEach(s=>{let a=s.a*(.75+.25*Math.sin(t*.001+s.tw));ctx.fillStyle=`rgba(190,215,220,${a})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()});shooters.forEach(s=>shooter(s,t));rocks.sort((a,b)=>a.z-b.z).forEach(o=>rock(o,t));requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
